#!/usr/bin/env node
/**
 * Fresh and frozen meat, poultry and fish are two products (Naor, 28.9: "כן תפריד טרי וקפוא"): fresh wings
 * at 12.90 and frozen at 7.90 are not one kilo to compare, and a shopper who wants fresh does not want
 * frozen. The backend reads concepts straight from config/concepts/*.json, so the frozen side has to be real
 * concept entries, not something the pipeline derives at run time.
 *
 * This script keeps them in step with the fresh concepts they mirror, so a rule is edited once:
 *   - every concept listed in type-words.json `frozenTwins.concepts` refuses the frozen words in its `none`;
 *   - config/concepts/meat-fish-frozen.json holds one `<id>-frozen` twin per listed concept: the same rules,
 *     plus the frozen words as one more `all` pattern, and the same category, size and kind.
 *
 *   node scripts/frozen-twins.mjs           write both
 *   node scripts/frozen-twins.mjs --check   exit 1 if either is out of step (test/frozenTwins.test.js runs it)
 *
 * Edit the fresh concept, then run the script; never edit meat-fish-frozen.json by hand.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'config', 'concepts');
const OUT_FILE = 'meat-fish-frozen.json';
const SKIP = new Set(['families.json', 'index.json', 'type-words.json', OUT_FILE]);

const readRaw = (file) => readFileSync(path.join(DIR, file), 'utf8');
const serialize = (json, like) => JSON.stringify(json, null, 1) + (like === undefined || like.endsWith('\n') ? '\n' : '');

export function frozenTwinPlan(dir = DIR) {
  const typeWords = JSON.parse(readFileSync(path.join(dir, 'type-words.json'), 'utf8'));
  const { word, concepts: ids = [], label = 'קפוא' } = typeWords.frozenTwins ?? {};
  if (!word) throw new Error('type-words.json has no frozenTwins.word');
  const wanted = new Set(ids);
  const files = new Map(); // file -> { raw, json, changed }
  const bases = new Map(); // id -> concept (after the fresh-side edit)
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json') && !SKIP.has(f))) {
    const raw = readFileSync(path.join(dir, file), 'utf8');
    const json = JSON.parse(raw);
    const list = Array.isArray(json) ? json : json.concepts ?? [];
    let changed = false;
    for (const c of list) {
      if (!wanted.has(c.id)) continue;
      c.match.none ??= [];
      if (!c.match.none.includes(word)) { c.match.none.push(word); changed = true; }
      bases.set(c.id, c);
    }
    files.set(file, { raw, json, changed });
  }
  const missing = ids.filter((id) => !bases.has(id));
  if (missing.length) throw new Error(`frozenTwins lists concepts that do not exist: ${missing.join(', ')}`);
  const twins = ids.map((id) => {
    const c = bases.get(id);
    const { none = [], ...rest } = c.match;
    return {
      id: `${id}-frozen`,
      name: `${c.name} (${label})`,
      category: c.category,
      sizeUnit: c.sizeUnit ?? null,
      ...(c.defaultSize !== undefined ? { defaultSize: c.defaultSize } : {}),
      synonyms: [...new Set((c.synonyms?.length ? c.synonyms : [c.name]).map((s) => `${s} ${label}`))],
      ...(c.kind ? { kind: c.kind } : {}),
      match: { ...rest, all: [...(c.match.all ?? []), word], none: none.filter((p) => p !== word) },
    };
  });
  const out = {
    _doc: 'Generated by scripts/frozen-twins.mjs from the fresh concepts listed in type-words.json frozenTwins - do not edit by hand. Fresh and frozen are two products (Naor, 28.9).',
    concepts: twins,
  };
  return { files, out, word };
}

function run(check) {
  const { files, out } = frozenTwinPlan();
  const stale = [];
  for (const [file, { raw, json, changed }] of files) {
    if (!changed) continue;
    stale.push(file);
    if (!check) writeFileSync(path.join(DIR, file), serialize(json, raw));
  }
  let outRaw = null;
  try { outRaw = readRaw(OUT_FILE); } catch { /* first run */ }
  const outText = serialize(out);
  if (outRaw !== outText) { stale.push(OUT_FILE); if (!check) writeFileSync(path.join(DIR, OUT_FILE), outText); }
  const indexRaw = readRaw('index.json');
  const index = JSON.parse(indexRaw);
  if (!index.files.includes(OUT_FILE)) {
    stale.push('index.json');
    if (!check) { index.files.splice(index.files.indexOf('meat-fish.json') + 1, 0, OUT_FILE); writeFileSync(path.join(DIR, 'index.json'), serialize(index, indexRaw)); }
  }
  if (check && stale.length) { console.error(`frozen twins out of step: ${stale.join(', ')} - run node scripts/frozen-twins.mjs`); process.exit(1); }
  console.log(check ? `frozen twins in step (${out.concepts.length})` : `frozen twins: ${out.concepts.length}${stale.length ? `, wrote ${stale.join(', ')}` : ', nothing to change'}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) run(process.argv.includes('--check'));
